# Generated by Django 2.2.1 on 2019-09-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('act_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('act_time', models.DateTimeField()),
                ('act_ops', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'action_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BkList',
            fields=[
                ('bk_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('bk_date', models.CharField(max_length=45)),
                ('bk_st', models.CharField(max_length=45)),
                ('bk_ed', models.CharField(blank=True, max_length=45, null=True)),
                ('wh_bk', models.CharField(max_length=45)),
                ('adult', models.CharField(max_length=45)),
                ('children', models.CharField(max_length=45)),
                ('bk_ps', models.CharField(blank=True, max_length=45, null=True)),
                ('tk_service', models.CharField(max_length=45)),
                ('is_cancel', models.CharField(max_length=45)),
                ('entire_time', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'bk_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('social_id', models.CharField(max_length=45, unique=True)),
                ('username', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('prod_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=45)),
                ('prod_img', models.CharField(max_length=100)),
                ('prod_price', models.PositiveIntegerField(blank=True, null=True)),
                ('prod_desc', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'production',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=45)),
                ('staff_id_num', models.CharField(max_length=10, unique=True)),
                ('staff_phone', models.CharField(max_length=10)),
                ('staff_birth', models.DateField()),
                ('staff_gender', models.CharField(max_length=45)),
                ('staff_address', models.CharField(max_length=45)),
                ('staff_email', models.CharField(max_length=45)),
                ('staff_level', models.PositiveIntegerField()),
                ('staff_age', models.PositiveIntegerField()),
                ('staff_skills', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'staff',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=45)),
                ('store_address', models.CharField(max_length=45)),
                ('store_phone', models.CharField(max_length=20)),
                ('store_fax', models.CharField(blank=True, max_length=20, null=True)),
                ('tk_service', models.IntegerField()),
                ('stay_time', models.IntegerField()),
                ('pay_md', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'store',
                'managed': False,
            },
        ),
    ]
