# Generated by Django 2.2.1 on 2019-09-27 08:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('checkbooking', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActionLog',
        ),
        migrations.DeleteModel(
            name='BkList',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Production',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
