# Generated by Django 2.2.3 on 2019-10-02 17:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user_id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('social_id', models.CharField(blank=True, max_length=45, null=True)),
                ('social_app', models.CharField(blank=True, max_length=45, null=True)),
                ('username', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=10)),
                ('birth', models.DateField(blank=True, null=True)),
                ('created_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'acc___db',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=45)),
                ('store_address', models.CharField(max_length=45)),
                ('store_phone', models.CharField(max_length=20)),
                ('store_fax', models.CharField(blank=True, max_length=20, null=True)),
                ('tk_service', models.IntegerField()),
                ('stay_time', models.IntegerField()),
                ('pay_md', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'db_table': 'store___db',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=45)),
                ('staff_id_num', models.CharField(max_length=10, unique=True)),
                ('staff_phone', models.CharField(max_length=10)),
                ('staff_birth', models.DateField()),
                ('staff_gender', models.CharField(max_length=45)),
                ('staff_address', models.CharField(max_length=45)),
                ('staff_email', models.CharField(max_length=45)),
                ('staff_level', models.PositiveIntegerField()),
                ('staff_age', models.PositiveIntegerField()),
                ('staff_skills', models.CharField(blank=True, max_length=45, null=True)),
                ('staff_created', models.DateTimeField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='booking.Store')),
            ],
            options={
                'db_table': 'staff___db',
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('prod_uuid', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=45)),
                ('prod_img', models.CharField(max_length=100)),
                ('prod_price', models.PositiveIntegerField(blank=True, null=True)),
                ('prod_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='booking.Store')),
            ],
            options={
                'db_table': 'prod___db',
            },
        ),
        migrations.CreateModel(
            name='BkList',
            fields=[
                ('bk_uuid', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('bk_date', models.DateField()),
                ('bk_st', models.TimeField()),
                ('bk_ed', models.TimeField(blank=True, null=True)),
                ('wh_bk', models.DateTimeField()),
                ('adult', models.PositiveIntegerField()),
                ('children', models.PositiveIntegerField()),
                ('bk_ps', models.CharField(blank=True, max_length=200, null=True)),
                ('tk_service', models.IntegerField()),
                ('is_cancel', models.IntegerField()),
                ('entire_time', models.IntegerField()),
                ('waiting_num', models.PositiveIntegerField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='booking.Store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='booking.Account')),
            ],
            options={
                'db_table': 'bk_list___db',
            },
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('act_id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('act_time', models.DateTimeField()),
                ('act_ops', models.CharField(max_length=45)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='booking.Store')),
            ],
            options={
                'db_table': 'action_log___db',
            },
        ),
    ]
