# Generated by Django 2.2.3 on 2019-10-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_id',
            field=models.CharField(default=None, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='act_id',
            field=models.CharField(default=None, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bklist',
            name='bk_uuid',
            field=models.CharField(default=None, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='production',
            name='prod_uuid',
            field=models.CharField(default=None, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(default=None, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_id',
            field=models.CharField(default=None, max_length=36, primary_key=True, serialize=False),
        ),
    ]
