# Generated by Django 2.2.3 on 2019-10-07 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bklist',
            name='entire_time',
        ),
        migrations.RemoveField(
            model_name='bklist',
            name='tk_service',
        ),
        migrations.AddField(
            model_name='bklist',
            name='event_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bklist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='booking.Account'),
        ),
        migrations.CreateModel(
            name='AccountLog',
            fields=[
                ('acclog_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('wh_happen', models.DateTimeField(blank=True, null=True)),
                ('acc_oops', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='booking.Account')),
            ],
            options={
                'db_table': 'acc_log___db',
            },
        ),
    ]
