# Generated by Django 2.2.1 on 2019-09-27 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Account',
        ),
        migrations.AlterModelTable(
            name='account',
            table='account',
        ),
    ]
