# Generated by Django 2.2.3 on 2019-10-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='social_name',
            field=models.CharField(default=None, max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bklist',
            name='bk_habit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
