# Generated by Django 2.2.3 on 2019-10-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20191007_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_name',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
