# Generated by Django 2.2.1 on 2019-10-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20191003_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='act_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='bklist',
            name='wh_bk',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_created',
            field=models.DateTimeField(default=None),
        ),
    ]
