# Generated by Django 2.2.3 on 2019-10-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20191008_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='bklist',
            name='time_session',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
