# Generated by Django 2.2.3 on 2019-10-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_bklist_time_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='bklist',
            name='entire_time',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='end_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='social_app',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='social_id',
            field=models.CharField(default=None, max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id_num',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
