# Generated by Django 2.2.3 on 2019-10-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20191008_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='bklist',
            name='bk_price',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
    ]
