# Generated by Django 2.2.3 on 2019-10-13 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_bklist_bk_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreEvent',
            fields=[
                ('event_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=45)),
                ('event_date', models.DateTimeField()),
                ('time_session', models.CharField(max_length=45)),
                ('event_created', models.DateTimeField(blank=True, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='booking.Store')),
            ],
            options={
                'db_table': 'store_event___db',
            },
        ),
    ]
