# Generated by Django 2.2.3 on 2019-10-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20191013_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='bklist',
            name='is_comfirm',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
