# Generated by Django 2.2.3 on 2019-10-23 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('social_id', models.CharField(blank=True, max_length=45, null=True)),
                ('social_app', models.CharField(blank=True, max_length=45, null=True)),
                ('username', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=10)),
                ('birth', models.DateField(blank=True, null=True)),
                ('social_name', models.CharField(max_length=45)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'acc___db',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=45, unique=True)),
                ('store_address', models.CharField(max_length=45)),
                ('store_phone', models.CharField(max_length=20)),
                ('store_fax', models.CharField(blank=True, max_length=20, null=True)),
                ('tk_service', models.IntegerField()),
                ('stay_time', models.IntegerField()),
                ('pay_md', models.CharField(blank=True, max_length=4, null=True)),
                ('seat', models.PositiveIntegerField()),
                ('store_created', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'store___db',
            },
        ),
        migrations.CreateModel(
            name='StoreEvent',
            fields=[
                ('event_id', models.CharField(default=None, max_length=45, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=45)),
                ('event_date', models.DateField()),
                ('time_session', models.CharField(max_length=45)),
                ('event_created', models.DateTimeField(blank=True, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Store')),
            ],
            options={
                'db_table': 'store_event___db',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('social_id', models.CharField(max_length=45)),
                ('social_app', models.CharField(blank=True, max_length=45, null=True)),
                ('staff_name', models.CharField(max_length=45)),
                ('staff_id_num', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('staff_phone', models.CharField(blank=True, max_length=10, null=True)),
                ('staff_birth', models.DateField(blank=True, null=True)),
                ('staff_gender', models.CharField(max_length=45)),
                ('staff_address', models.CharField(blank=True, max_length=200, null=True)),
                ('staff_email', models.CharField(max_length=100)),
                ('staff_level', models.PositiveIntegerField()),
                ('staff_age', models.PositiveIntegerField(blank=True, null=True)),
                ('staff_skills', models.CharField(blank=True, max_length=45, null=True)),
                ('staff_created', models.DateTimeField(blank=True, null=True)),
                ('staff_ended', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Store')),
            ],
            options={
                'db_table': 'staff___db',
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('prod_uuid', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=45)),
                ('prod_img', models.CharField(max_length=100)),
                ('prod_price', models.PositiveIntegerField(blank=True, null=True)),
                ('prod_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('prod_created', models.DateTimeField(blank=True, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Store')),
            ],
            options={
                'db_table': 'prod___db',
            },
        ),
        migrations.CreateModel(
            name='BkList',
            fields=[
                ('bk_uuid', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('bk_date', models.DateField()),
                ('time_session', models.CharField(max_length=10)),
                ('bk_st', models.TimeField()),
                ('bk_ed', models.TimeField(blank=True, null=True)),
                ('wh_bk', models.DateTimeField(blank=True, null=True)),
                ('adult', models.PositiveIntegerField()),
                ('children', models.PositiveIntegerField()),
                ('bk_ps', models.CharField(blank=True, max_length=200, null=True)),
                ('bk_habit', models.CharField(blank=True, max_length=200, null=True)),
                ('event_type', models.CharField(blank=True, max_length=20, null=True)),
                ('is_cancel', models.IntegerField()),
                ('waiting_num', models.PositiveIntegerField()),
                ('entire_time', models.IntegerField()),
                ('bk_price', models.PositiveIntegerField()),
                ('is_confirm', models.IntegerField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Store')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Account')),
            ],
            options={
                'db_table': 'bk_list___db',
            },
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('act_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('act_time', models.DateTimeField(blank=True, null=True)),
                ('act_ops', models.CharField(max_length=45)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Staff')),
            ],
            options={
                'db_table': 'action_log___db',
            },
        ),
        migrations.CreateModel(
            name='AccountLog',
            fields=[
                ('acclog_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('wh_happen', models.DateTimeField(blank=True, null=True)),
                ('acc_oops', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Account')),
            ],
            options={
                'db_table': 'acc_log___db',
            },
        ),
    ]
