# Generated by Django 2.2.6 on 2019-11-21 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='staff_birth',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='staff_level',
        ),
    ]
