# Generated by Django 2.2.6 on 2020-01-15 17:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('f4f2d321-36be-4453-90a2-00b025b62264'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bklist',
            name='bk_uuid',
            field=models.UUIDField(default=uuid.UUID('a69c71bb-fb27-47fa-b2b9-bc5a9199d9e3'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='production',
            name='prod_id',
            field=models.UUIDField(default=uuid.UUID('10bf39c2-a52e-415f-aa0f-6e5a4ae04bd8'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.UUIDField(default=uuid.UUID('105f67ca-892a-4c24-8401-4e9c9c63d301'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_id',
            field=models.UUIDField(default=uuid.UUID('c825b578-ea64-4098-baa3-946601aa024e'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='storeevent',
            name='event_id',
            field=models.UUIDField(default=uuid.UUID('92260c98-e18c-4069-98f4-551993637807'), primary_key=True, serialize=False),
        ),
    ]
