# Generated by Django 2.2.1 on 2019-10-29 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='staff',
            table='staff___db',
        ),
    ]
