# Generated by Django 2.2.6 on 2019-11-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191107_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='level',
            field=models.CharField(default=None, max_length=45),
            preserve_default=False,
        ),
    ]
