# Generated by Django 2.2.6 on 2019-11-09 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191109_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='production',
            old_name='prod_uuid',
            new_name='prod_id',
        ),
    ]
