# Generated by Django 2.2.6 on 2019-11-21 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191122_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffactionlog',
            name='staff',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useractionlog',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Account'),
            preserve_default=False,
        ),
    ]
